### ISSUE TITLE
Prepare Solidus Shipstation for Solidus 3.0

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_shipstation#6]
Update this extension so that it works with Solidus 3.0 by making sure the specs pass.

**Comment by AlistairNorman** [comment]
I'll take this one!

**Comment by AlistairNorman** [comment]
Tests pass without deprecations already! Moved this one right up to have no deprecated code since as far as I can tell no work is needed on this one.

**Comment by seand7565** [comment]
@AlistairNorman Awesome, thanks for looking into it! 🎉
